//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class baZVaEntities : DbContext
    {
        private static baZVaEntities _context;
        public baZVaEntities()
            : base("name=baZVaEntities")
        {
        }
        public static baZVaEntities GetContext()
        {
            if (_context == null)
                _context = new baZVaEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Commpanys> Commpanys { get; set; }
        public virtual DbSet<Nottes> Nottes { get; set; }
        public virtual DbSet<Reminders> Reminders { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Ussers> Ussers { get; set; }
    }
}
