//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminders
    {
        public int ReminderID { get; set; }
        public string ReminderText { get; set; }
        public Nullable<System.DateTime> ReminderTime { get; set; }
    
        public virtual Ussers Ussers { get; set; }
    }
}
